spring:
  profiles:
    active: development
  application:
    name: NOTIFICATION-SERVICE
     
  data:
    mongodb:
      uri: "mongodb+srv://cryptobankhub:dn5KpCLxe7J3Gu9d@cryptobankhub.gv9a2cv.mongodb.net/?retryWrites=true&w=majority"
      database: Cbh-Notification
      
server:
  port: 1016
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---

spring:
  config:
    activate:
      on-profile: development
         
  jpa:
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: cryptobankhub@gmail.com
    password: yolmpacybtucqvca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false