server:
  port: 1010

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
        - id: CRYPTO-SERVICE
          uri: lb://CRYPTO-SERVICE
          predicates:
            - Path=/crypto/**
            
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
            
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
            
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
            
        - id: KEYCLOAK-SERVICE
          uri: lb://KEYCLOAK-SERVICE
          predicates:
            - Path=/keycloak/**
            
        - id: BANK-SERVICE
          uri: lb://BANK-SERVICE
          predicates:
            - Path=/bankaccount/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

    

